<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation" Version="10.4.0" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="10.4.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.3.10" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.16" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="DependencyInjection\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\HackNewsApp.Domain\HackNewsApp.Domain.csproj" />
  </ItemGroup>

</Project>
